IN = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

IN = open('input.txt').read()

beams = ["."] * len(IN.splitlines()[0])
total = 0
for line in IN.splitlines():
  print("".join(beams))
  print("".join(line))
  for i,v in enumerate(line):
    if v == 'S':
      beams[i] = '|'
    if v == '^' and beams[i] == '|':
      beams[i] = ' '
      beams[i-1] = '|'
      beams[i+1] = '|'
      total += 1


    # if v in 'S' or (v in '|' and beams[i] == '|')]:
    # beams[i] = '|'

print(total)
